CREATE DATABASE University
USE University
		   
CREATE TABLE Majors
(
	MajorID INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL

)

CREATE TABLE Students
(
	StudentID INT PRIMARY KEY NOT NULL,
	StudentNumber NVARCHAR(10) NOT NULL,
	StudentName NVARCHAR(50) NOT NULL,
	MajorID INT NOT NULL,

	FOREIGN KEY (MajorID) REFERENCES Majors(MajorID)
)
CREATE TABLE Payments
(
	PaymentID INT PRIMARY KEY NOT NULL,
	PaymentDate DATETIME NOT NULL,
	PaymentAmount MONEY NOT NULL,
	StudentID INT NOT NULL,

	FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
)
CREATE TABLE [Subjects]
(
	SubjectID INT PRIMARY KEY NOT NULL,
	SubjectName NVARCHAR(50)
)

CREATE TABLE Agenda
(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL,
	CONSTRAINT PK_STUDENTIT_SUBJECTID PRIMARY KEY(StudentID,SubjectID),

	FOREIGN KEY (StudentID) REFERENCES Students(StudentID),
	FOREIGN KEY (SubjectID) REFERENCES Subjects(SubjectID)
)

